name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '50 4 * * *'

env:
  # disable incremental compilation.
  #
  # incremental compilation is useful as part of an edit-build-test-edit cycle,
  # as it lets the compiler avoid recompiling code that hasn't changed. however,
  # on CI, we're not making small edits; we're almost always building the entire
  # project from scratch. thus, incremental compilation on CI actually
  # introduces *additional* overhead to support making future builds
  # faster...but no future builds will ever occur in any given CI environment.
  #
  # see https://matklad.github.io/2021/09/04/fast-rust-builds.html#ci-workflow
  # for details.
  CARGO_INCREMENTAL: 0
  # allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). this should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  # terminal colors are nice
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10
  # don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short
  rust-toolchain: nightly

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - name: rust toolchain
        run: rustup show active-toolchain; cargo --version; rustc --version
      - name: cargo build
        run: cargo build --all-features --message-format=json | cargo-action-fmt
      - name: cargo test
        run: cargo test --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - name: rust toolchain
        run: rustup show active-toolchain; cargo --version; rustc --version
      - name: cargo clippy
        run: cargo clippy --all-features --message-format=json | cargo-action-fmt

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - name: rust toolchain
        run: rustup show active-toolchain; cargo --version; rustc --version
      - name: cargo fmt
        run: cargo fmt --check --message-format=json | cargo-action-fmt